on:
  workflow_dispatch
  
name: buildAPI
jobs:
  csvBuild:
    runs-on: ubuntu-latest
    container: docker://geogdan/geoboundaries:A
    steps:        
    - name: Download Metadata
      run: |
           cd $GITHUB_WORKSPACE
           cd ..
           ls
           git clone --filter=blob:none --no-checkout https://github.com/wmgeolab/geoBoundaries
           echo "=============="
           cd geoBoundaries
           echo "=============="
           git sparse-checkout init "*.csv"
           git sparse-checkout add "releaseData/geoBoundariesOpen-meta.csv"
           git sparse-checkout add "releaseData/geoBoundariesHumanitarian-meta.csv"
           git sparse-checkout add "releaseData/geoBoundariesAuthoritative-meta.csv"
           git checkout 
   
    - name: Clone the website repository
      run: |
            cd ..
            ls
            pwd
            git clone https://github.com/wmgeolab/gbWeb.git
            cd gbWeb
   
    - name: Build CSV
      id: checks
      run: |
           echo "==============================================="
           mkdir ~/tmp 
           mkdir ~/artifacts
           python assets/python/apiBuild.py
      env:
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
           
    - name: Commit Files
      env:
            DRTOKEN: ${{secrets.DRTOKEN}}
            REP: ${{env.GITHUB_REPOSITORY}}
      run: |
           ls
           pwd
           git status
           git config --local user.email "danr@wm.edu"
           git config --local user.name "DanRunfola"
           git add -A .
           git remote set-url origin https://x-access-token:${{ secrets.DRTOKEN }}@github.com/$GITHUB_REPOSITORY
           git diff-index --quiet HEAD || git commit -m "geoBoundary Status and Build Script"
           git status
           git push origin main 


