on:
  workflow_dispatch
name: DeployAPI
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - name: Download Changes
      run: |
           cd $GITHUB_WORKSPACE
           cd ..
           rm -r gbWeb
           git clone https://github.com/wmgeolab/gbWeb
             
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://ftp.geoboundaries.org/geoboundaries.org/api/
        ftp-username: geologs
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: api
        #git-ftp-args: --dry-run